name: Deploy to NuGet

on:
  push:
    tags:
    - '*'
    
env:  
  CONFIG: "Release"
  NUGET_SOURCE_URL: "https://nuget.pkg.github.com/esteveslean/index.json"
  PROJECT_PATH: "src/Dotnet.NuanceTranscription.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  
jobs:
  deploy:
    name: "deploy to nuget"
    runs-on: ubuntu-latest    
    steps:
    - name: "checkout"
      uses: actions/checkout@v2
    
    - name: "install dotnet"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: "restore packages"
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: "build project"
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration ${{ env.CONFIG }}
      
    - name: "test project"
      run: dotnet test ${{ env.PROJECT_PATH }} --configuration ${{ env.CONFIG }} --no-build --verbosity normal
      
    - name: 'get version'
      id: version
      uses: battila7/get-version-action@v2  
      
    - name: 'pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration ${{ env.CONFIG }} --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'push package'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
